version: '3'

services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes: 
            - ./laravel:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - laravel
            - mysql
        networks: 
            - "${NETWORK_NAME}"

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            SERVICE_TAGS: "${MYSQL_SERVICE_TAGS}"
            SERVICE_NAME: "${MYSQL_SERVICE_NAME}"
        networks: 
            - "${NETWORK_NAME}"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        restart: unless-stopped
        ports:
            - "15672:15672"
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - ${NETWORK_NAME}

    laravel:
        build:
            context: laravel
            dockerfile: ../docker/laravel/Dockerfile
        container_name: laravel
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_HOST: ${RABBITMQ_HOST}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
            RABBITMQ_DEFAULT_PORT: ${RABBITMQ_PORT}
        volumes:
            - ./laravel:/var/www/app
        ports: 
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks: 
            - "${NETWORK_NAME}"

    mailer:
        build:
            context: ./mailer
            dockerfile: ../docker/mailer/Dockerfile
        container_name: mailer
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_HOST: ${RABBITMQ_HOST}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
            RABBITMQ_DEFAULT_PORT: ${RABBITMQ_PORT}
            MAILER_USERNAME: ${MAILER_USERNAME}
            MAILER_USER_PASSWORD: ${MAILER_USER_PASSWORD}
            MAILER_USER_HOST: ${MAILER_USER_HOST}
            MAILER_EMAIL_ADDRESS: ${MAILER_EMAIL_ADDRESS}
            MAILER_EMAIL_NAME: ${MAILER_EMAIL_NAME}
            MAILER_PORT: ${MAILER_PORT}
        volumes:
            - ./mailer:/var/www/app
        ports:
            - "${PHP_MAILER_HOST_PORT}:${PHP_MAILER_DOCKER_CONTAINER_PORT}"
        networks:
            - "${NETWORK_NAME}"
        command: "${MAILER_START_COMMAND}"

networks:
    laravel:
        driver: bridge